### ISSUE TITLE
Name Clash

### ISSUE THREAD

**Issue by axelbr** [OpenDriveLab/Vista#1]
Are you aware of [Vista](https://vista.csail.mit.edu/)?

**Comment by Little-Podi** [comment]
Hi, we are aware of that series of works. It is a wonderful simulation engine. On the other hand, our work tries to build a generalizable world model. We believe that there are enough distinctions between these two works to let the community distinguish them easily.

**Comment by axelbr** [comment]
I was not claiming that your approach is not different enough. I was just thinking that, given your knowledge about vista, the similarity in the domain and the task both approaches aim to solve, it is odd to choose the same name.

**Comment by axelbr** [comment]
Anyways, I am excited and look forward to trying out your model once it has been made public.

**Comment by Little-Podi** [comment]
FYI, we have just shared the model weights. Welcome to give it a try.
