### ISSUE TITLE
How can I use it on NuScenes mini?

### ISSUE THREAD

**Issue by GulpFire** [OpenDriveLab/Vista#10]
I want to test it on mini dataset, what should I do to adapt annos file to support mini dataset?

**Comment by Little-Podi** [comment]
The samples in mini dataset are included in the full set, whose annotations are given. Therefore, I think those frames can be retrieved by going through our JSON files and finding the corresponding filenames. Note that the FID and FVD scores could be much lower if you only evaluate on a subset.

**Comment by GulpFire** [comment]
> The samples in mini dataset are included in the full set, whose annotations are given. Therefore, I think those frames can be retrieved by going through our JSON files and filtering the corresponding filenames. Note that the FID and FVD scores could be much higher if you only evaluate on a subset.

Thanks

**Comment by Little-Podi** [comment]
You are welcome :)

**Comment by WuZhongQing** [comment]
> The samples in mini dataset are included in the full set, whose annotations are given. Therefore, I think those frames can be retrieved by going through our JSON files and filtering the corresponding filenames. Note that the FID and FVD scores could be much higher if you only evaluate on a subset.

Hi，i want to ask that can i just use the ann files that you provided to train nuscenesMini ?

**Comment by Little-Podi** [comment]
Yes, as long as you have the file names mapped.

**Comment by WuZhongQing** [comment]
> Hi @WuZhongQing, it is practical as long as you have the filenames mapped.

thanks a lot ~
