### ISSUE TITLE
Question about long-horizon generation

### ISSUE THREAD

**Issue by woodfrog** [OpenDriveLab/Vista#14]
Hi, great work and thank you for open-sourcing! On your [visualization page](https://vista-demo.github.io/), you showed results of 50 frames (5s * 10FPS) and 160 frames (16s * 10FPS), and I have some questions regarding the long-horizon generation:

(1). What are the parameters to change for generating these variable-length videos? Is it only the ``n_rounds``? I tried with ``n_rounds=6`` following the doc, but the average video quality looks obviously worse than the ones on the visualization page. I wonder are there other things that we should set up?

(2). Both 50 and 160 are not ``25 + 22 * (n_rounds-1)``, so what are the settings to generate a 16s video with FPS=10? Do you set ``n_rounds`` to 7 and take the first 160 frames, or do you change the ``n_frames`` as well?

Thank you!

**Comment by lilligao** [comment]
Also thank you for open sourcing and really great work! 
I was also encountering the same issue here. I tried to do the sampling with the nuscenes dataset and the video quality also looks pretty bad. 
I have also another question regarding the commands. What does the commands 0, 1, 2, 3 stand for? I didn't find it in the codebase. 
I guess 0 is turn right, 1 is turn left, 2 is stop and 3 is driving forward. Is that right? 
Thank you so much :)!!

**Comment by Little-Podi** [comment]
Hi there, thanks for your interest. Sorry for the late reply, I had an extremely busy week.

> What are the parameters to change for generating these variable-length videos? Is it only the n_rounds? I tried with n_rounds=6 following the doc, but the average video quality looks obviously worse than the ones on the visualization page. I wonder are there other things that we should set up?

Yes, the length of prediction is controlled by `n_rounds`. There is no special argument for this. The failure case always exists. I am planning to release a version that has been trained for a longer time, but do not expect too much. However, it is noteworthy that if the same process is applied to SVD, its results will be much worse compared with ours, especially in terms of content continuity.

> Both 50 and 160 are not 25 + 22 * (n_rounds-1), so what are the settings to generate a 16s video with FPS=10? Do you set n_rounds to 7 and take the first 160 frames, or do you change the n_frames as well?

Sorry for confusion. On our demo page, the videos in the first section contain 25 + 22 * (2 - 1) = 47 frames, and the videos in the second section contain 25 + 22 * (7 - 1) = 157 frames. Hope these can solve your questions.

**Comment by woodfrog** [comment]
> Hi there, thanks for your interest. Sorry for the late reply, I had an extremely busy week.
> 
> > What are the parameters to change for generating these variable-length videos? Is it only the n_rounds? I tried with n_rounds=6 following the doc, but the average video quality looks obviously worse than the ones on the visualization page. I wonder are there other things that we should set up?
> 
> Yes, the length of prediction is controlled by `n_rounds`. There is no other special argument for this. The failure case always exists. I am planning to release a version that has been trained for a longer time, but do not expect too much. However, it is noteworthy that if the same process is applied to [SVD](https://stability.ai/research/stable-video-diffusion-scaling-latent-video-diffusion-models-to-large-datasets), its results will be much worse compared with ours, especially in terms of content continuity.
> 
> > Both 50 and 160 are not 25 + 22 * (n_rounds-1), so what are the settings to generate a 16s video with FPS=10? Do you set n_rounds to 7 and take the first 160 frames, or do you change the n_frames as well?
> 
> Sorry for confusion. On our demo page, the videos in the first section contain 25 + 22 * (2 - 1) = 47 frames, and the videos in the second section contain 25 + 22 * (7 - 1) = 157 frames. Hope these can solve your questions.

Thank you for the answers!
