### ISSUE TITLE
Where is annos/YouTube.json ?

### ISSUE THREAD

**Issue by F-Barto** [OpenDriveLab/Vista#17]
Train and val json for NuScenes are available on google drive but I can't find annos/YouTube.json.

Am I missing something or is it just not available ?

**Comment by Little-Podi** [comment]
It's not available. We split the YouTube data to multiple disks, to the way we organize the dataset is not generally applicable. In addition, we do not annotate the YouTube data. Therefore, you only need to download the YouTube videos, transform them into images, and compile the paths as JSON files.

**Comment by F-Barto** [comment]
Thank you for your answer ! 

I am not interested in annotations.

My question, in particular for OpenDV, is how do you split the dataset ? How do you extract the 25 frames clips, and how do you manage the overlap between clips if any ?

In nuscenes, it seems you extracted clips of 25 frames from sequences, sometimes with overlap (some frames appears multiple time in different clips). Each dict in the json is a sample, a clip of 25 frames.

It is not clear how is it done for OpenDV (and nuPlan).

**Comment by Little-Podi** [comment]
Thanks for your question.

> My question, in particular for OpenDV, is how do you split the dataset ? How do you extract the 25 frames clips, and how do you manage the overlap between clips if any ?

We first extract the videos into images at 10 Hz. Then, starting from each single image, we combine it with the 24 following frames (if available) to form a clip. The last 24 frames in each video will not be used as the initial frame. For example, for a video with 1000 frames at 10 Hz, there will be (1000 - 24) = 976 video clips eventually. The adjacent video clips will have overlaps, but they are different to the model.

> It is not clear how is it done for OpenDV (and nuPlan).

nuPlan is not involved to train Vista. We only use a filtered set of OpenDV-Youtube.

**Comment by F-Barto** [comment]
That's very clear ! Thank you very much for these precisions : )
