### ISSUE TITLE
Some confusion about training example

### ISSUE THREAD

**Issue by YuzhiChen001** [OpenDriveLab/Vista#21]
Hi, it's really a nice work! 
I want to know whether nusc_train.yaml contains both Phase 1: learning high-fidelity future prediction and Phase 2: learning versatile action controllability with Stage 1: low-resolution training、 Stage 2: high-resolution training, or only is one of the above?

**Comment by Little-Podi** [comment]
Thanks for your interest! The example configuration contains only a single stage for debugging and does not belong to any stages used in the paper. It is similar to "Phase 1 `+` action conditions" or "Phase 2 Stage 2 `-` LoRA layers".

**Comment by YuzhiChen001** [comment]
Thank you for your patient answer！
