### ISSUE TITLE
some questions about the data processing

### ISSUE THREAD

**Issue by unicoco7** [OpenDriveLab/Vista#25]
I have some questions about the dataset processing. In the NUS dataset, each frame of the photo should correspond to the speed, trajectory, angle, yaw, position, etc., of each frame. I would like to ask how your nusScenes_val.json was generated. I see that in the file, each sample is 25 frames of photos, corresponding to 5 angles and 10 speeds. Could you please explain how each indicator is calculated?
~~~python
    {
        "frames": [
            "samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151514512404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151514612404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151514662404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151514762404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151514862404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151514912404.jpg",
            "samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151515012404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151515112404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151515162404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151515262404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151515362404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151515412404.jpg",
            "samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151515512404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151515612404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151515662404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151515762404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151515862404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151515912404.jpg",
            "samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151516012404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151516112404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151516162404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151516262404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151516362404.jpg",
            "sweeps/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151516412404.jpg",
            "samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151516512404.jpg"
        ],
        "traj": [
            -2.2737367544323206e-13,
            -2.2737367544323206e-13,
            -1.208763251270284e-05,
            -9.999039718877611e-05,
            0.0001486184571604099,
            -0.00014122429581675533,
            9.823742470871366e-05,
            1.0633676026827743e-05,
            0.00036040194186170993,
            9.846511198929875e-05
        ],
        "speed": [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0
        ],
        "angle": [
            -19.799999999999727,
            -19.799999999999727,
            -19.799999999999727,
            -19.799999999999727,
            -19.799999999999727
        ],
        "cmd": 2,
        "z": -0.7426007053248327,
        "goal": [
            782.7996047483739,
            -2035.1494645306138
        ]
    },
~~~

**Comment by unicoco7** [comment]
The current control commands are limited to four. I would like to perform some more refined command operations, such as turning left, which can be divided into (turning left at an intersection and lane-changing left turn). How should I write a JSON file to complete the test I want to conduct? Thank you very much.

**Comment by unicoco7** [comment]
I noticed in your paper that you mentioned normalizing the angle to the range of [-1, 1], yet the range of the Steer Angle Feedback is [-7.7, 6.3]. I also noticed that in your dataset, you divided the angle of NuScence by 780. May I ask how you performed the normalization? Was it already transformed to [-1, 1] before being inputted? Or was it processed after being fed into the neural network? Additionally, is your normalization method the min-max scaling?

**Comment by unicoco7** [comment]
Additionally, I would like to ask why these four control methods cannot coexist and must be chosen one out of the four? Aren't they all transformed into vectors for embedding?

**Comment by Little-Podi** [comment]
> May I understand it this way: 'Angle' refers to the 'Steer Angle Feedback' of the CAN bus, and 'Speed' refers to the 'vel' of the Pose?

Not really, "angle" and "speed" correspond to "steering" and "vehicle_speed" respectively in [CAN bus Vehicle Monitor](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/can_bus#vehicle-monitor).

> May I ask how you performed the normalization? Was it already transformed to [-1, 1] before being inputted? Or was it processed after being fed into the neural network? Additionally, is your normalization method the min-max scaling?

The range of steering angle in CAN bus is [-780, 779.9], so I divided it by 780 to ensure that the resulting value does not exceed [-1, 1]. The normalization is performed before inputting the condition into the model.

> I would like to ask why these four control methods cannot coexist and must be chosen one out of the four? Aren't they all transformed into vectors for embedding?

Sorry for the confusion. They are transformed and concatenated together. The action conditions can coexist if all ground truth annotations are known (e.g., samples within the nuScenes dataset). However, for open-world scenarios during test, obtaining multiple equivalent action conditions seems impossible since the parameters of the camera and the vehicle are unavailable. For instance, when a user prompts the model with a trajectory, it is extremely hard to derive a corresponding goal point simultaneously. Therefore, I think it is more practical for users to provide only one action condition each time.

**Comment by unicoco7** [comment]
Thank you so so so much！
