### ISSUE TITLE
about how to generate multi_view video ?

### ISSUE THREAD

**Issue by WuZhongQing** [OpenDriveLab/Vista#28]
hi thanks for your reply,  i had read your sample code , but i cannot find out how to generate multi_view video, could you tell me how to organize my data or change code in sample.py.   Looking forward to your reply ^_^

**Comment by Little-Podi** [comment]
Unfortunately, multi-view generation is not a feature of Vista. We focus on front-view generation to leverage diverse data sources.

**Comment by Little-Podi** [comment]
You are welcome :)
