### ISSUE TITLE
Get stuck at loading FrozenCLIPEmbedder or FrozenOpenCLIPImageEmbedder

### ISSUE THREAD

**Issue by shuimushan** [OpenDriveLab/Vista#29]
I have tried to operate as 'issue.md' suggested and replace the _version_ with the paths of pytorch_model.bin but still get the following error:
RuntimeError: Error(s) in loading state_dict for CLIP:
        Missing key(s) in state_dict: "positional_embedding", "text_projection", "visual.class_embedding", "visual.positional_embedding", "visual.proj", "visual.conv1.weight", "visual.ln_pre.weight", "visual.ln_pre.bias", "visual.transformer.resblocks.0.ln_1.weight",  ……

It seems that the weights was not successfully loaded, but I have no idea how to solve this problem. Could you please give me some suggestions?

**Comment by Little-Podi** [comment]
Are you loading the correct checkpoint from the provided Hugging Face link? The model dictionary should match perfectly without extra keys.

**Comment by shuimushan** [comment]
> Are you loading the correct checkpoint from the provided Hugging Face link? The model dictionary should match perfectly without extra keys.

I think so. The 3.7G pytorch_model.bin corresponds to the OpenCLIPImageEmbedder and the 1.6G pytorch_model.bin corresponds to the OpenCLIPEmbedder, is that right? And I am confused that even the "positional_embedding" key is missing.

**Comment by shuimushan** [comment]
I find another [open_clip_pytorch_model.bin](https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/blob/main/open_clip_pytorch_model.bin) instead of the one I downloaded [pytorch_model.bin](https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/blob/main/pytorch_model.bin). May the first one be correct?

**Comment by Little-Podi** [comment]
Yes! For FrozenOpenCLIPImageEmbedder, you should use open_clip_pytorch_model. I will correct the instructions. Thanks for pointing this issue.

**Comment by shuimushan** [comment]
Thanks you very much! It works.
