### ISSUE TITLE
Action annotation from NuScenes

### ISSUE THREAD

**Issue by samueleruffino99** [OpenDriveLab/Vista#3]
Hello! Amazin work!

I was wondering, how did you extract high-level action commands for NuScenes ("stop", "turn right" and so on). i have red some details in Section C.2, but can you also give details on the time conmsidered for such actions, or what do you mean for forawrd driving distance from nuscenes?
Moreover, do you think that the same approach as yours with SVD+ControlNet would work?
I have also seen that all other works uses others form of conditioning (e.g., bounding boxes of other objects, lane in BEV, ...). Are you using rgb frames only (+ actions) instead?

Thank you very much!

![Screenshot 2024-05-30 164339](https://github.com/OpenDriveLab/Vista/assets/127489168/a488c0ed-b1f7-4ae9-b82f-34cdcb9a98ad)

**Comment by Little-Podi** [comment]
Yes, I think that different types of conditions exhibit different characteristics, and certain solutions are better suited for specific condition signals. However, as long as you training continues long enough, I think that multiple approaches can yield satisfactory results.

For additional action projections, I simply expand the dimension of the cross-attention layers to enable longer key and value inputs. You may refer to the implementation here:
https://github.com/OpenDriveLab/Vista/blob/main/vwm/modules/attention.py#L319-L324

I will release the scripts together with the necessary JSON files for training on nuScenes. I took a little rest this week, but I will work on releasing more stuffs as soon as possible.

Hope these are helpful :)

**Comment by Little-Podi** [comment]
Hi, we have released all the scripts for training and sampling. Any feedback is appreciated!

**Comment by Little-Podi** [comment]
Yes, we have provided all translated actions on nuScenes [here](https://github.com/OpenDriveLab/Vista/blob/main/docs/INSTALL.md#preparation).

**Comment by Little-Podi** [comment]
BTW, you can also generate the ground truth trajectory and command on your own using the following code:
https://github.com/OpenDriveLab/ST-P3/blob/main/stp3/datas/NuscenesData.py#L505-L532

**Comment by samueleruffino99** [comment]
Thank you very much!!

**Comment by Little-Podi** [comment]
Actually, I'm not very familiar with those specific parameters, and I didn't notice Kappa before. I choose steering angle just to follow previous works (DriveGAN, DriveDreamer, etc.) and because it is directly available from [CAN bus](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/can_bus). I may consider Kappa as a feature in future versions. The method should be the same.

**Comment by zxduan90** [comment]
"traj": [
            2.842170943040401e-14,
            0.0,
            0.004099807857556925,
            1.721318810349203,
            0.003575851106660366,
            3.6442674844633984,
            0.003844690624902114,
            6.042236588326432,
            0.019102743037507253,
            8.828964143841404
        ],
I think this traj should be cmd 0, but in nuscenes.json, its action is cmd 3

**Comment by Little-Podi** [comment]
Hi @zxduan90,

Sorry for the confusion. The mapping between displacements and commands is: "turn right" -> `0`, "turn left" -> `1`, "stop" -> `2`, "go straight" -> `3`. Therefore, the given translation is correct.

**Comment by zxduan90** [comment]
> Hi @zxduan90,
> 
> Sorry for the confusion. The mapping between displacements and commands is: "turn right" -> `0`, "turn left" -> `1`, "stop" -> `2`, "go straight" -> `3`. Therefore, the given translation is correct.

@Little-Podi Thanks for replay.

**Comment by Little-Podi** [comment]
I'm closing this issue due to its inactivity. Free feel to reopen it if you have further questions.
