### ISSUE TITLE
about condition 'Z' in provided json.

### ISSUE THREAD

**Issue by WuZhongQing** [OpenDriveLab/Vista#31]
Hi, sorry for ask so many questions ~. 
I know all the key except 'z', could you please tell me the meaning of 'z' ? And i guess its the  zero-init projection ?
![image](https://github.com/user-attachments/assets/ebcd1185-ed4f-482d-928a-39b850daf673)

**Comment by Little-Podi** [comment]
Any questions are welcome! The "z" represents the "depth" value after 3D-to-2D projection. It is used to identify whether the projected goal point falls within the front-view frame or not. If it is negative, the goal point of this sample is considered invalid. You can check our implementation [here](https://github.com/OpenDriveLab/Vista/blob/main/vwm/data/subsets/nuscenes.py#L74).

**Comment by WuZhongQing** [comment]
> Any questions are welcome! The "z" represents the "depth" value after 3D-to-2D projection. It is used to identify whether the projected goal point falls within the front-view frame or not. If it is negative, the goal point of this sample is considered invalid. You can check our implementation [here](https://github.com/OpenDriveLab/Vista/blob/main/vwm/data/subsets/nuscenes.py#L74).

thanks for your reply, that's very clear ~

**Comment by Little-Podi** [comment]
You are welcome :)
