### ISSUE TITLE
Inference phase-1 model

### ISSUE THREAD

**Issue by liuallen871219** [OpenDriveLab/Vista#33]
Currently, I am working on training phase-1 of Vista on our custom dataset. I want to know if any method exists for the inference phase-1 model in the repos. Besides, Is the phase-1 pre-trained model of Vista available for downloading?

Thanks.

**Comment by Little-Podi** [comment]
Hi @liuallen871219, we didn't upload the phase1 checkpoint. However, you can load the final model with the phase1 configuration. The weights related to action control can be omitted, and I believe the model will function similarly as phase1.
