### ISSUE TITLE
a question about action control on new scenes.

### ISSUE THREAD

**Issue by WuZhongQing** [OpenDriveLab/Vista#34]
hi,i'm trying to control the direction of the car, and i used the command like this (and used image not in nuScene):

![image](https://github.com/user-attachments/assets/dba1f574-9a36-44d3-856f-08d277ee8d37)

in the same time, i changed the code in "sampe.py",like:

![image](https://github.com/user-attachments/assets/dfc15a67-cfae-4ea1-ac14-26e3a58e3b77)

but it doesn't work, the output of video doesn't change anything.
cloud you please explain that ~
And i think the reason is all of your traing data has only one direction when traing phase 2 , is that a reasonable explaination ?^_^

**Comment by WuZhongQing** [comment]
and i had tried control the direction by using traj, it worked ~

**Comment by Little-Podi** [comment]
Thanks for your question! As mentioned in the appendix, the chance of failure persists in action control. Our model has better controllability for trajectory, angle, and speed conditions but is slightly worse for command and goal point conditions. The reason could be the limited diversity among training samples, as you said. To enable successful command control, I recommend trying a scenario where the ego vehicle arrives in front of a crossroad (or a place where turning can occur).
