### ISSUE TITLE
average l2 error definition

### ISSUE THREAD

**Issue by Fengtao22** [OpenDriveLab/Vista#35]
Hi, thanks again for your open-source work! I have one question with respect to the definition of L2 used in Fig. 10 of your paper. In particular, what is the definition of the **average L2 error**? I tried to random spawn the 4 waypoints (2 seconds) with a gaussian distribution using mean as the ground truth and standard deviation to be 0.5 (treating x, y as independent variables). The resulted L2 is around 1.35+/-0.35 (for 1k random samples) and this L2 is calculated based on      

_torch.norm(gt_8_values_list - sampled_8_values_list, p=2).item()_ 

where the 8 values in the list corresponds to [x_0.5, y_0.5, x_1, y_1, x_1.5, y_1.5, x_2, y_2].

My average L2 error is way bigger than what shown in your Fig 10.

**Comment by Little-Podi** [comment]
Hi @Fengtao22, I really appreciate your interest to our work!

The average L2 errors are not pre-defined. You need to manually adjust the jittering deviation to obtain a well-distributed L2 error sequence. I just made a clarification of how I do this part in #32, please check it out and let me know if you have any other questions.
