### ISSUE TITLE
Questions about

### ISSUE THREAD

**Issue by fjq-tongji** [OpenDriveLab/Vista#36]
Hello authors! When the parameter 'n_round' is set to 6, why the total frames are 135？According to my shallow understanding, each additional round extends the prediction by 2.3 seconds, so when the n_round is 6, the total time is 2.3*(6-1)+2.5=14 seconds. However, the results show that it is 13.5 seconds, I am confused.

**Comment by YTEP-ZHI** [comment]
Hi @fjq-tongji, good question! This is because the last 3 frames of each predicted clip will be the starting frames of the next clip, in an autoregressive manner. So the total number of frames = 6 (rounds) * 25 (n_frames per round) - (6 - 1) * 3 (number of connective frames)
