### ISSUE TITLE
A question about the datasets used for the second stage

### ISSUE THREAD

**Issue by zhoujiawei3** [OpenDriveLab/Vista#39]
Hi, thank you for your excellent work!
I would like to try training in the second stage. This stage requires nuscenes and opendv data, but opendv is too large for the second stage. I noticed that opendv-mini has been released; can I use opendv-mini to replace opendv if I’m only focused on fine-tuning in the second stage?

**Comment by Little-Podi** [comment]
Thanks for your interest!

> can I use opendv-mini to replace opendv if I’m only focused on fine-tuning in the second stage?

Yes, you can use OpenDV-mini to maintain generalization when learning action controllability.

**Comment by zhoujiawei3** [comment]
Thanks for your reply, I will try it
