### ISSUE TITLE
What is Z means in action

### ISSUE THREAD

**Issue by zhoujiawei3** [OpenDriveLab/Vista#42]
![image](https://github.com/user-attachments/assets/b752eeb4-6f12-41fb-ad96-2f6ded6aa70b)
Hi. Can you explain what z means in action. Morever, is the goal in json is given with respect to the global coordinate system?

**Comment by Little-Podi** [comment]
> Can you explain what z means in action.

Please take a look at #31.

> Morever, is the goal in json is given with respect to the global coordinate system?

No, it is the 2D coordinate of the front-view image.

**Comment by Little-Podi** [comment]
> I'm still unsure about the position of the origin point—is it in the middle of the image?

The origin point is the position of the ego vehicle in the start frame.

> Could you please provide the code to obtain the pair of the goal and Z?

The code to derive these annotations can be found at #30.

**Comment by zhoujiawei3** [comment]
Thanks for your help!!
