### ISSUE TITLE
A question about the dynamic prior in stage 2 training.

### ISSUE THREAD

**Issue by zhoujiawei3** [OpenDriveLab/Vista#43]
From the config, I know the dynamic prior in stage 2 training fixed on 1. 
![image](https://github.com/user-attachments/assets/9573c4c2-13f2-4856-9b35-aa8ff7091b7f)
I wonder why don't you set the dynamic prior multi-combinated, just the same as the stage 1 training？

**Comment by zhoujiawei3** [comment]
Thanks. I also want to ask where I can set the probailities of the dynamic prior. I don't find similar value in the configs.
![image](https://github.com/user-attachments/assets/de97ee4a-9ba6-43f4-a9c7-a278054ac7b8)

**Comment by YTEP-ZHI** [comment]
@zhoujiawei3 
The probabilities for each type of conditioning are set here: https://github.com/OpenDriveLab/Vista/blob/6ff19b805c646e050414567425728aac4257d767/vwm/modules/diffusionmodules/loss.py#L74-L77

**Comment by YTEP-ZHI** [comment]
> @zhoujiawei3 The probabilities for each type of conditioning are set here, namely, `weights`:
> 
> https://github.com/OpenDriveLab/Vista/blob/6ff19b805c646e050414567425728aac4257d767/vwm/modules/diffusionmodules/loss.py#L74-L77

**Comment by zhoujiawei3** [comment]
Thank you very much for your help！
