### ISSUE TITLE
About the annos files

### ISSUE THREAD

**Issue by Yang-Jianzhang** [OpenDriveLab/Vista#44]
Would you release the code which generating the `annos` files? (`nuScenes.json` and `nuScenes_val.json`)

**Comment by YTEP-ZHI** [comment]
Hi @Yang-Jianzhang, please refer to this thread with code included: https://github.com/OpenDriveLab/Vista/issues/30

**Comment by Yang-Jianzhang** [comment]
> Hi @Yang-Jianzhang, please refer to this thread with code included: #30

Oh, sorry. I missed this issues.
Thank you very much~
