### ISSUE TITLE
nuScenes sampling not working correctly.

### ISSUE THREAD

**Issue by seamie6** [OpenDriveLab/Vista#46]
Hello,
I am trying to use your model, namely the ```sample.py``` but it is not working as intended. Some params I have changed is ```low_vram``` is True, and I reduced the image size to save on space to ```(128,256)```. However when I run the model the output is very strange, perhaps I have a misunderstanding as to how the model works. 
But when i provide the 25 images, the prediction and GT are as so:

Ground Truth:
![NUSCENES_000000_0001](https://github.com/user-attachments/assets/f364a190-5c72-4b25-8cd8-8a48217865a8)
![NUSCENES_000000_0002](https://github.com/user-attachments/assets/e1442cf4-866e-4800-bb81-d31b79e94412)
![NUSCENES_000000_0003](https://github.com/user-attachments/assets/16a389f1-3cd8-4e7b-91c8-8f57da645956)
![NUSCENES_000000_0004](https://github.com/user-attachments/assets/017efac1-f707-4c79-8b58-0c7dfae5d9f5)

Predicted:
![NUSCENES_000000_0003](https://github.com/user-attachments/assets/df213733-15f0-48da-82b2-9b770dcc89e7)
![NUSCENES_000000_0004](https://github.com/user-attachments/assets/8fec728b-cb8b-402a-aee0-7aa146fbcc3d)
![NUSCENES_000000_0005](https://github.com/user-attachments/assets/8b5871c2-db2b-41ad-988e-3498a0a94927)
![NUSCENES_000000_0006](https://github.com/user-attachments/assets/e361c5ab-5556-48f6-9b29-df0132b9176a)

I thought it takes temporal context and so will continue after a certain point. But it seems like it does not do this.
Additionally, I then changed ```cond_frames``` to 10 as I thought this would solve it. But for the predicted frames, the first 10 frames are the GT, which i expected as they are given as context. But the predicted 15 frames continue from the first frame where the front of the truck is barely in sight, similar to the predicted seen in the images provided.

**Comment by YTEP-ZHI** [comment]
The model has never been trained on that aspect ratio (128/256), thus it's hard to generalize on that resolution. We suggest using resolutions of 320×576 or 576×1024, which the model has been trained on.

**Comment by seamie6** [comment]
Ok understood. Are there any sample runs to show what it should look like on the full image size? I cannot find a demo for nuScenes on the repo

**Comment by seamie6** [comment]
https://huggingface.co/spaces/rerun/Vista
It seems the link is broken to try the example on HuggingFace, I will try locally hopefully sometime soon. Thanks
