### ISSUE TITLE
Data on nuscenes

### ISSUE THREAD

**Issue by lianglia-apollo** [OpenDriveLab/Vista#5]
First, appreciate for open source this project. 

Could you elaborate which dataset is needed on https://www.nuscenes.org/download to reproduce this work?

**Comment by Little-Podi** [comment]
Hi. Please download all splits of **Trainval** in **Full dataset (v1.0)**, including the `sweeps` set.
![image](https://github.com/OpenDriveLab/Vista/assets/96873712/a3deedef-a0c4-497b-8a1b-4ae25b717c2c)
To replicate our performance, we recommend also downloading **OpenDV-YouTube** dataset from [DriveAGI](https://github.com/OpenDriveLab/DriveAGI#genad-dataset-opendv-youtube) if possible. You can start with a few YouTubers like [J Utah](https://www.youtube.com/@jutah/videos). Feel free to let us know if you encounter any troubles.

**Comment by MulitiByte** [comment]
> Hi. Please download all splits of **Trainval** in **Full dataset (v1.0)**, including the `sweeps` set. ![image](https://private-user-images.githubusercontent.com/96873712/337464959-a3deedef-a0c4-497b-8a1b-4ae25b717c2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTgzODYsIm5iZiI6MTcyMDUxODA4NiwicGF0aCI6Ii85Njg3MzcxMi8zMzc0NjQ5NTktYTNkZWVkZWYtYTBjNC00OTdiLThhMWItNGFlMjViNzE3YzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA5NDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMTRiZmViMDA1ZTJiMmUxM2ZkNGI0NjIwNzZhNTJmZWVlN2UwODRmN2M1MzZlMTk0YWFiZWJkNDI0MzUxNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9koMQGHY_6SY3av8_XeYgnWIBbX8MQGMPJ47FG4XwRc) To replicate our performance, we recommend also downloading **OpenDV-YouTube** dataset from [DriveAGI](https://github.com/OpenDriveLab/DriveAGI#genad-dataset-opendv-youtube) if possible. You can start with a few YouTubers like [J Utah](https://www.youtube.com/@jutah/videos). Feel free to let us know if you encounter any troubles.

Hi, I also want to experiences the pretrained model to see the generated videos based on NuScenes. Howerver I enconter a problem seemingly from dataset.

Loading model from ckpts/vista.safetensors
Global seed set to 23
Traceback (most recent call last):
  File "/data/workspace/code/Vista-main/sample.py", line 254, in <module>
    img = load_img(each_path, opt.height, opt.width)
  File "/data/workspace/code/Vista-main/sample.py", line 197, in load_img
    image = Image.open(file_name)
  File "/root/anaconda3/envs/vista/lib/python3.9/site-packages/PIL/Image.py", line 3277, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/data/workspace/data/nuScenes/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151514512404.jpg'

I only download the first two of all parts.
 Could you please provide a more detailed dataset organization structure after that  I have downloaded all of the 10 parts of Nuscenes. (I note that all part files have directory'sample','sweep', should I manually merge them into the same directory?)

**Comment by Little-Podi** [comment]
Hi @MulitiByte, thanks for your interest. Yes, I think you need to merge them all to fit the annotations.

**Comment by MulitiByte** [comment]
> Hi @MulitiByte, thanks for your interest. Yes, I think you need to merge them all to fit the annotations.

Thank you so much for your kind an patient reply. I have successfully  tested on my own machine. And I have some more questions, I set the configurations for sampling as follows:

 action='free',
 n_rounds=1, 
n_frames=16, 
n_conds=3, 
seed=46, 
height=320, 
width=576, 
cfg_scale=2.5, 
cond_aug=0.0,
 n_steps=50, 
rand_gen=True, low_vram=False

Some produced videos are a little unnatural, could you please provide some advice acorrding to your practical experiences to help to improve the quality? Thanks a lot !
(BTW:  dose the parameter n_conds means using the first three frames as the condition for the whole 16 frames under this config?)

**Comment by Little-Podi** [comment]
Hi @MulitiByte, I think the main factor is the number of frames you use. It is not recommended to set `n_frames` less than 25 if you have enough GPT memory.

**Comment by Little-Podi** [comment]
I'm closing this issue due to its inactivity. Free feel to reopen it if you have further questions.
