### ISSUE TITLE
Only test on nuscenes?

### ISSUE THREAD

**Issue by IranQin** [OpenDriveLab/Vista#6]
Can it be tested on any given AD video using text conditions?

**Comment by Little-Podi** [comment]
> on any given AD video

Certainly. I am not sure what kind of video format you want to use, but the easiest way would be to extract the initial frame and set the `--dataset` argument of the sampling script as [IMG](https://github.com/OpenDriveLab/Vista/blob/main/docs/SAMPLING.md).

> using text conditions

Our model does not accept textual inputs, as text can be unintuitive and ambiguous when specifying actions in the task of autonomous driving.

**Comment by IranQin** [comment]
Isn't the commend in the paper given as text?

**Comment by IranQin** [comment]
Could you provide a mapping between the command and category of [0,1,2,3] ?

**Comment by Little-Podi** [comment]
Hi, we translate trajectories into commands following [ST-P3](https://github.com/OpenDriveLab/ST-P3). Please refer to this issue https://github.com/OpenDriveLab/Vista/issues/3 for details.

**Comment by Little-Podi** [comment]
I'm closing this issue due to its inactivity. Free feel to reopen it if you have further questions.
